global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:8000"]

  - job_name: "journal-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["journal-service:8000"]