apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "auth-service-k8s"
        metrics_path: /metrics
        static_configs:
          - targets:
              - auth-service.devops-platform.svc.cluster.local:8000

      - job_name: "product-service-k8s"
        metrics_path: /metrics
        static_configs:
          - targets:
              - product-service.devops-platform.svc.cluster.local:8000