name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Auth Service image
        run: docker build -t auth-service ./services/auth-service

      - name: Build Journal Service image
        run: docker build -t journal-service ./services/journal-service